export {
  premiseKindLabel,
  premiseMemberRoleLabel,
  premiseBookedAsKindLabel,
  slotBookedAs,
  slotStatusLabel,
  isoDate,
  monthKey,
  formatSlotTime,
  slotsForDay,
  slotDotsByDate,
  monthRangeIso,
  toDatetimeLocalValue,
  fromDatetimeLocalValue,
  decodeUploadedFileName,
  agreementDocumentKindLabel,
} from "./model/premise-utils";

export type {
  PremiseTab,
  AvailabilityFormDay,
  RentalScheduleFormDay,
  FreePremiseInterval,
  SlotFormState,
  UpcomingSlotGroup,
} from "./model/premise-detail-types";

export {
  roleOptions,
  statusOptions,
  paymentStatusOptions,
  premiseKindOptions,
  usageTypeOptions,
  recurrenceTypeOptions,
  weekDays,
  paymentStatusLabel,
  usageTypeLabel,
  rentalStatusLabel,
  agreementStatusLabel,
} from "./model/premise-detail-options";

export {
  createAvailabilityForm,
  createRentalScheduleForm,
  pickDefaultBookingActor,
  bookingActorValue,
  parseBookingActorValue,
  creatorContactDefaults,
  emptySlotForm,
  slotToForm,
} from "./model/premise-detail-forms";

export {
  minutesToTime,
  timeToMinutes,
  formatDuration,
  slotBookingRentalId,
  rentalContactLabel,
  formatRentalDate,
  groupUpcomingSlots,
  buildCancelRentalWarning,
  formatRubles,
  getPremiseSlotActorLabel,
  getOrganizationInitials,
  normalizeMemberEmail,
  resolvePremiseMemberLabel,
  calculateFreeIntervals,
  extractError,
  buildPremiseSlotsQueryRange,
  collectMemberEmails,
  collectSlotPeopleEmails,
  mergeUniqueEmails,
  buildMemberProfileByEmail,
  filterActiveSlots,
  filterPendingSlots,
  filterTodaySlots,
  computeOccupiedHours,
  computeOccupiedDays,
  computeUnpaidAmountRub,
  canEditPremiseSlot,
  validateSlotForm,
  buildEnabledSchedules,
  buildSlotUpdatePayload,
  buildCreateRentalPayload,
  validateSettingsForm,
  buildUpdatePremiseBody,
  applyFreeIntervalToSlotForm,
} from "./model/premise-detail-helpers";

export { BookedAsBadge } from "./ui/BookedAsBadge";

export {
  useListPremisesQuery,
  useGetPremiseQuery,
  useCreatePremiseMutation,
  useUpdatePremiseMutation,
  useDeletePremiseMutation,
  useListPremiseRentalsQuery,
  useGetPremiseRentalQuery,
  useCreatePremiseRentalMutation,
  useCreatePremiseRentalAgreementMutation,
  useGeneratePremiseRentalAgreementMutation,
  useUpdatePremiseRentalPaymentMutation,
  useUpdatePremiseRentalStatusMutation,
  useUploadPremiseRentalAgreementMutation,
  useListPremiseSlotsQuery,
  useCreatePremiseSlotMutation,
  useUpdatePremiseSlotMutation,
  useDeletePremiseSlotMutation,
  useListPremiseMembersQuery,
  useAddPremiseMemberMutation,
  useUpdatePremiseMemberMutation,
  useRemovePremiseMemberMutation,
} from "./api/premises-api";
