/** Теги кэша RTK Query — добавляйте домены по мере миграции sync/api. */
export const orchestraApiTagTypes = [
  "Dashboard",
  "Rehearsal",
  "RehearsalList",
  "RehearsalScenes",
  "RehearsalPlan",
  "Profile",
  "ProfileBatch",
  "ProjectRoles",
  "ProjectMembers",
  "ProductionTeam",
  "Troupe",
  "Premises",
  "PremiseSlots",
  "PremiseMembers",
  "DirectorSessions",
  "ProjectMaterial",
  "ProjectTasks",
  "SyncPull",
  "ActorAnnotations",
  "ChatConversation",
  "ChatMessages",
  "ActorSceneNote",
  "AccountingCollections",
  "AccountingContributions",
  "Studios",
  "StudioDetail",
  "StudioInvites",
  "StudioAssignments",
  "StudioLessons",
  "StudioVideos",
  "Billing",
] as const;
