/** Теги кэша RTK Query — добавляйте домены по мере миграции sync/api. */
export const orchestraApiTagTypes = [
  "Rehearsal",
  "RehearsalList",
  "RehearsalScenes",
  "RehearsalPlan",
  "Profile",
  "ProfileBatch",
  "ProjectRoles",
  "ProjectMembers",
  "Troupe",
  "Premises",
  "PremiseSlots",
  "PremiseMembers",
  "DirectorSessions",
  "ProjectMaterial",
  "ProjectTasks",
  "SyncPull",
  "ActorAnnotations",
] as const;
